### ISSUE TITLE
Automate data transformation for production

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-gnd#16]
We have to automate our data transformation setup for production mode:

- [x] Baseline transformation and indexing, log ~~errors, monitor log~~
- [x] Update transformation, indexing, logging ~~, monitoring~~. See also commit comment for  00ca2a6bed848eae632c7b4d3e0a18ef9d9f518f

~~Both could be triggered via curl POSTs from a cron job (like in lobid-organisations). Calling the transformation from within the web app would result in logging to the application.log (currently calling classes with main methods manually for transformations).~~

- [ ] ~~Set up routes and controllers for triggering baseline and update transformations~~
- [x] Set up dates to pass to the updates transformation, see also commit comment for  00ca2a6bed848eae632c7b4d3e0a18ef9d9f518f
- [x] Set up cron jobs for triggering the baseline and updates transformation

Server side setup should probably wait until https://github.com/hbz/lobid-webserver/issues/5 is done.

**Comment by fsteeg** [comment]
Since we'll switch to a new approach for our workflow automation (see https://github.com/hbz/lobid/issues/354) I have not done major changes to the current setup in lobid-gnd, see strikeouts and checkboxes in the comment above. Updates are sheduled to run tonight, will check results tomorrow.

**Comment by fsteeg** [comment]
Both http://lobid.org/gnd/search and http://stage.lobid.org/gnd/search are now based on the latest GND baseline from 2017-10-04. Scheduled updates failed, there's a dependency issue when running sbt:

```
sbt 'runMain apps.ConvertUpdates 2017-10-04'
[...]
[error] (run-main-0) java.lang.NoClassDefFoundError: org/apache/xpath/XPathAPI
java.lang.NoClassDefFoundError: org/apache/xpath/XPathAPI
	at ORG.oclc.oai.harvester2.verb.HarvesterVerb.getSingleString(HarvesterVerb.java:295)
	at ORG.oclc.oai.harvester2.verb.HarvesterVerb.getSingleString(HarvesterVerb.java:281)
	at ORG.oclc.oai.harvester2.verb.HarvesterVerb.harvest(HarvesterVerb.java:262)
	at ORG.oclc.oai.harvester2.verb.HarvesterVerb.<init>(HarvesterVerb.java:183)
	at ORG.oclc.oai.harvester2.verb.Identify.<init>(Identify.java:48)
	at ORG.oclc.oai.harvester2.app.RawWrite.run(RawWrite.java:113)
	at apps.Convert$OpenOaiPmh.process(Convert.java:76)
	at apps.ConvertUpdates.lambda$main$0(ConvertUpdates.java:26)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at apps.ConvertUpdates.main(ConvertUpdates.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.ClassNotFoundException: org.apache.xpath.XPathAPI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at ORG.oclc.oai.harvester2.verb.HarvesterVerb.getSingleString(HarvesterVerb.java:295)
	at ORG.oclc.oai.harvester2.verb.HarvesterVerb.getSingleString(HarvesterVerb.java:281)
	at ORG.oclc.oai.harvester2.verb.HarvesterVerb.harvest(HarvesterVerb.java:262)
	at ORG.oclc.oai.harvester2.verb.HarvesterVerb.<init>(HarvesterVerb.java:183)
	at ORG.oclc.oai.harvester2.verb.Identify.<init>(Identify.java:48)
	at ORG.oclc.oai.harvester2.app.RawWrite.run(RawWrite.java:113)
	at apps.Convert$OpenOaiPmh.process(Convert.java:76)
	at apps.ConvertUpdates.lambda$main$0(ConvertUpdates.java:26)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at apps.ConvertUpdates.main(ConvertUpdates.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```

**Comment by fsteeg** [comment]
Fixed the dependency issue, set up SSH key for sol on weywot2, and manually triggered the cron.sh script. Both http://lobid.org/gnd/search and http://stage.lobid.org/gnd/search now have up-to-date data. Will verify scheduled updates next week before closing.

**Comment by fsteeg** [comment]
Automatic updates ran fine, for both http://lobid.org/gnd/search and http://stage.lobid.org/gnd/search (OAI-PMH interface is only used once, data is copied internally to stage, all happens starting nightly at 1 via https://github.com/hbz/lobid-gnd/blob/master/cron.sh, see crontab for sol@weywot1). Closing.
